In [1]:
pip install kinopoisk-dev

Requirement already satisfied: kinopoisk-dev in /usr/local/lib/python3.11/site-packages (0.2.0)
Requirement already satisfied: httpx<0.24.0,>=0.23.3 in /usr/local/lib/python3.11/site-packages (from kinopoisk-dev) (0.23.3)
Requirement already satisfied: pydantic<2.0.0,>=1.9.2 in /usr/local/lib/python3.11/site-packages (from kinopoisk-dev) (1.10.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/site-packages (from httpx<0.24.0,>=0.23.3->kinopoisk-dev) (2022.12.7)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in /usr/local/lib/python3.11/site-packages (from httpx<0.24.0,>=0.23.3->kinopoisk-dev) (0.16.3)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /usr/local/lib/python3.11/site-packages (from httpx<0.24.0,>=0.23.3->kinopoisk-dev) (1.5.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/site-packages (from httpx<0.24.0,>=0.23.3->kinopoisk-dev) (1.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.11/site-packages (from pydantic<2.0.0,>=1.9.2->kinopoisk-dev) (4.7.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/site-packages (from httpcore<0.17.0,>=0.15.0->httpx<0.24.0,>=0.23.3->kinopoisk-dev) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.11/site-packages (from httpcore<0.17.0,>=0.15.0->httpx<0.24.0,>=0.23.3->kinopoisk-dev) (3.7.1)
Requirement already satisfied: idna in /usr/local/lib/python3.11/site-packages (from rfc3986[idna2008]<2,>=1.3->httpx<0.24.0,>=0.23.3->kinopoisk-dev) (3.4)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: /usr/local/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
# connect to API Kinopoisk
from kinopoisk_dev import KinopoiskDev, MovieParams, MovieField

kp = KinopoiskDev(token='ZVEPHXS-QHPMTZ7-NC8ED8G-??????')
item = kp.find_many_movie(
        params=[
            MovieParams(keys=MovieField.PAGE, value=1),
            MovieParams(keys=MovieField.LIMIT, value=250),
        ]
    )

In [4]:
# transform data from kinopoisk to dataframe
import pandas as pd
df = pd.DataFrame(item) # to dataframe
df_main_movies = df.at[4, 1]
df_main_movies = pd.DataFrame(df_main_movies)

In [5]:
# update df_main_movies

def rename_columns_df_main_movies(film_stg):
    """return DF with renamed names columns"""
    columns = [x[0] for x in df_main_movies.values[0]]
    df_main_movies.columns = columns
    return df_main_movies


def update_rows_df_main_movies(film_stg):
    """ return DF with updated rows"""
     # give amount of columns
    amount_columns = df_main_movies.columns
    columns = [x[0] for x in df_main_movies.values[0]]
    for i in range(len(amount_columns)): # iterating by number of columns
        data = [x[i][1] for x in df_main_movies.values] # bypassing the column names in data rows
        new_column = pd.Series(data, name=columns[i]) # create Series for update "df_main_movies"
        df_main_movies.update(new_column)
    return df_main_movies


def del_trash_df_main_movies(df_main_movies):
    """return DF with deleted "trash" columns"""
    list_trash = ['names', 'typeNumber', 'description', 'shortDescription', 'slogan', 'status', 'votes', 'ratingMpaa', 'ageRating', 'logo',
    'poster', 'backdrop', 'videos', 'persons', 'reviewInfo', 'seasonsInfo', 'budget', 'fees', 'premiere', 'similarMovies',
    'sequelsAndPrequels', 'watchability', 'top10', 'top250', 'enName', 'facts', 'imagesInfo', 'productionCompanies',]
    for i in list_trash:
        df_main_movies.drop(i, axis= 1 , inplace= True)
    return df_main_movies

df_main_movies = rename_columns_df_main_movies(df_main_movies)
df_main_movies = update_rows_df_main_movies(df_main_movies)
df_main_movies = del_trash_df_main_movies(df_main_movies)
df_main_movies

,id,externalId,name,alternativeName,type,year,rating,movieLength,genres,countries,releaseYears
0,535341,kpHD='4127663ed234fa8584aeb969ceb02cd8' imdb='...,1+1,Intouchables,movie,2011,kp=8.808 imdb=8.5 tmdb=None filmCritics=6.8 ru...,112.0,"[name='драма', name='комедия', name='биография']",[name='Франция'],"(releaseYears, None)"
1,1143242,kpHD='47649cf90de74aca8da7eb5b17fc8a8a' imdb='...,Джентльмены,The Gentlemen,movie,2019,kp=8.55 imdb=7.8 tmdb=None filmCritics=6.5 rus...,113.0,"[name='криминал', name='комедия', name='боевик']","[name='Великобритания', name='США']","(releaseYears, None)"
2,462682,kpHD='4d05a2c799d34ac9bb644af70c8e5dc1' imdb='...,Волк с Уолл-стрит,The Wolf of Wall Street,movie,2013,kp=7.976 imdb=8.2 tmdb=None filmCritics=7.8 ru...,180.0,"[name='драма', name='криминал', name='биографи...",[name='США'],"(releaseYears, None)"
3,1318972,kpHD='48de522f4bc591d7baa92c12ce435265' imdb='...,Гнев человеческий,Wrath of Man,movie,2021,kp=7.594 imdb=7.1 tmdb=None filmCritics=6.3 ru...,119.0,"[name='боевик', name='триллер']","[name='Великобритания', name='США']","(releaseYears, None)"
4,41519,kpHD='492c446642bf8dc88f0abcb9a4b02f7f' imdb='...,Брат,"(alternativeName, None)",movie,1997,kp=8.296 imdb=7.8 tmdb=None filmCritics=7.6 ru...,100.0,"[name='драма', name='криминал', name='боевик']",[name='Россия'],"(releaseYears, None)"
...,...,...,...,...,...,...,...,...,...,...,...
245,694633,kpHD='42db652069676947a9e51e2c5260854d' imdb='...,Хоббит: Битва пяти воинств,The Hobbit: The Battle of the Five Armies,movie,2014,kp=7.879 imdb=7.4 tmdb=None filmCritics=6.3 ru...,144.0,"[name='фэнтези', name='приключения', name='бое...","[name='Новая Зеландия', name='США']","(releaseYears, None)"
246,5129252,kpHD='e08d09982f994cda8f2d600e942e49a0' imdb=N...,Беспринципные в деревне,"(alternativeName, None)",movie,2023,kp=6.48 imdb=0.0 tmdb=None filmCritics=0.0 rus...,90.0,[name='комедия'],[name='Россия'],[]
247,453406,kpHD='428ab138f7fc21c28497a33fc9c8140c' imdb='...,Безумный Макс: Дорога ярости,Mad Max: Fury Road,movie,2015,kp=7.828 imdb=8.1 tmdb=None filmCritics=8.6 ru...,120.0,"[name='боевик', name='фантастика', name='прикл...",[name='Австралия'],"(releaseYears, None)"
248,5273,kpHD='406ffa09a945d21287653f6f65bc4653' imdb='...,Шрэк 2,Shrek 2,cartoon,2004,kp=7.858 imdb=7.3 tmdb=None filmCritics=7.7 ru...,93.0,"[name='мультфильм', name='фэнтези', name='мело...","[name='США', name='Канада']","(releaseYears, None)"
249,690593,kpHD='429e00f561ff628aa49ba32afff9df87' imdb='...,Человек-паук: Возвращение домой,Spider-Man: Homecoming,movie,2017,kp=7.156 imdb=7.4 tmdb=None filmCritics=7.6 ru...,133.0,"[name='фантастика', name='боевик', name='прикл...",[name='США'],"(releaseYears, None)"

In [6]:
# transform column 'releaseYears'

releaseYears = df_main_movies['releaseYears'] # Series
col = len(releaseYears)
for n in range(col):
    object_ = releaseYears.loc[n]
    if object_ is None:
        pass
    elif len(object_) == 0:
         releaseYears.loc[n] = None
    else:
        for i in range(len(releaseYears.loc[n])):
            first = str(object_[i]).find("(")
            j = str(object_[i])[first+1:]
            j = j.split()
            releaseYears.loc[n] = j

In [7]:
# func names_rows

def names_rows(name_col, name_df):
    """return list for update dataframe"""
    full_list_rows_df = name_df[name_col].to_list() # to list full data from "name_df" for transform
    final_list_rows_df = []
    for rows_df in full_list_rows_df:
        new_list_rows_df_1 = (str(rows_df)).split(' ')
        for items_rows_df in new_list_rows_df_1:
            new_list_rows_df_2 = items_rows_df.split('=')
            for index in range(len(new_list_rows_df_2)):
                new_list_rows_df_2[index] = new_list_rows_df_2[index].replace("'",'')
            final_list_rows_df.append(new_list_rows_df_2)
    return final_list_rows_df

In [8]:
# create and update table "externalId"

def create_and_upgrade_df_externalId(raw_names_list):
    """return df_externalId with new columns and rows"""
    names_rows_list = [x for x in raw_names_list] # give list with names rows
    """ names_rows_list = [['kpHD', '4127663ed234fa8584aeb969ceb02cd8'], ['imdb', 'tt1675434'], ['tmdb', '77338'],......]"""
    names_columns_list = [x[0] for x in raw_names_list][0:3] # give list with names table "['kpHD', 'imdb', 'tmdb']"
    items_kpHD_list_ = []
    items_imdb_list_ = []
    items_tmdb_list_ = []
    for items in names_rows_list:
      if items[0] == names_columns_list[0]:
          items_kpHD_list_.append(items[1])
      elif items[0] == names_columns_list[1]:
          items_imdb_list_.append(items[1])
      elif items[0] == names_columns_list[2]:
          items_tmdb_list_.append(items[1])
    df_externalId.insert(loc=1, column=names_columns_list[0], value=items_kpHD_list_) # insert value rows in columns for DF "externalId"
    df_externalId.insert(loc=1, column=names_columns_list[1], value=items_imdb_list_)
    df_externalId.insert(loc=1, column=names_columns_list[2], value=items_tmdb_list_)
    del df_externalId[df_externalId.columns [0]]
    return df_externalId


df_externalId = df_main_movies.pop('externalId') # execute column "externalId" from "film_stg" for create new table "df_externalId"
df_externalId = pd.DataFrame(df_externalId)
raw_names_list = names_rows('externalId', df_externalId) # call def names_rows() for transform raw data from "df_externalId" and append into list "names"

df_externalId = create_and_upgrade_df_externalId(raw_names_list)

In [9]:
# check data
df_externalId

       tmdb        imdb                              kpHD
0     77338   tt1675434  4127663ed234fa8584aeb969ceb02cd8
1    522627   tt8367814  47649cf90de74aca8da7eb5b17fc8a8a
2    106646   tt0993846  4d05a2c799d34ac9bb644af70c8e5dc1
3    637649  tt11083552  48de522f4bc591d7baa92c12ce435265
4     20992   tt0118767  492c446642bf8dc88f0abcb9a4b02f7f
..      ...         ...                               ...
245  122917   tt2310332  42db652069676947a9e51e2c5260854d
246    None        None  e08d09982f994cda8f2d600e942e49a0
247   76341   tt1392190  428ab138f7fc21c28497a33fc9c8140c
248     809   tt0298148  406ffa09a945d21287653f6f65bc4653
249  315635   tt2250912  429e00f561ff628aa49ba32afff9df87

[250 rows x 3 columns]